### ISSUE TITLE
Have you considered to use http://asciidoc.org/ as a source format?

### ISSUE THREAD

**Issue by vlsi** [nitish81299/spdx-pdf-html-template#13]
TeX and Pandoc do sound like an overkill.

**Comment by shnitish** [comment]
Sorry but I didn't get you. Can you explain a bit about your approach ?

**Comment by vlsi** [comment]
For instance, Gradle's documentation is written in Asciidoc format.

Input file: https://raw.githubusercontent.com/gradle/gradle/master/subprojects/docs/src/docs/userguide/java_plugin.adoc

Here's how GitHub renders it out of the box: https://github.com/gradle/gradle/blob/master/subprojects/docs/src/docs/userguide/java_plugin.adoc

Output file on the website: https://docs.gradle.org/current/userguide/java_plugin.html

Apparently that is much more convenient to read/write and maintain than TeX

**Comment by nitish81299** [comment]
I am sorry but I am bit lost here. My project is to convert spdx licence files which are in markdowns into PDF format. Not sure how ascii doc will help us here.

**Comment by shnitish** [comment]
@vlsi I am sorry but I am bit lost here. My project is to converts spdx licence files which are in markdowns to PDF format. Not sure how ascii doc will help us here
